### ISSUE TITLE
Moz Meter CSS Issue

### ISSUE THREAD

**Issue by arobillard** [arobillard/confectionery-website-prototype#2]
@thomasjbradley, issue related to the meter property in Firefox. It is also an issue in Safari. Opera is working and I have not yet tested Edge but will do once I am on my desktop.

Thanks.

**Comment by thomasjbradley** [comment]
https://css-tricks.com/html5-meter-element/
https://codepen.io/pankajparashar/pen/LceIj?editors=1100

**Comment by thomasjbradley** [comment]
I think I've got it figured out!

With this CSS here, I can render the image into the `<meter>` in Firefox.

```css
meter {
  -moz-appearance: none;
  -webkit-appearance: none;
  appearance: none;

  background: url("https://placehold.it/100x25") transparent;
}

meter::-moz-meter-bar {
  background: none;
}
```

I think the important thing is that, in Firefox, the meterbar doesn’t show the image through it, but renders as an opaque object. So we need to insert the image as a `background-image` to get it to render properly. It also seems to be critical to use the `background` property not just `background-image` and `background-color`.

For fallback purposes, it’s probably still a good idea to put the `<img>` inside the `<meter>` like you already have. I know that makes a little bit of code duplication, but I think it’s a good choice.

**Comment by arobillard** [comment]
Thanks! I got it to sort of work on Firefox with a bit of a sketchy work around (I think I might not be linking to the image correctly the first time). However, I can only seem to make it work on one browser at a time (either Chrome or Firefox, and never on Safari or Edge). I may just cut my losses and just a div for this project.

Thanks!

**Comment by thomasjbradley** [comment]
This should work in all browsers—I even tested it.

```css
meter {
  -moz-appearance: none;
  -webkit-appearance: none;
  appearance: none;
  background: url("https://placehold.it/100x25") transparent;
}

meter::-moz-meter-bar {
  background: none;
}

meter::-webkit-meter-optimum-value {
  background: none;
}

meter::-webkit-meter-bar {
  background: none;
}
```

And I think that you should just get rid of the internal image.
